# Generated by Django 5.2.5 on 2025-08-19 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MCPServer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('transport', models.CharField(choices=[('stdio', 'stdio'), ('streamable_http', 'streamable_http'), ('sse', 'sse'), ('websocket', 'websocket')], max_length=32)),
                ('url', models.TextField(blank=True, null=True)),
                ('command', models.TextField(blank=True, null=True)),
                ('args_json', models.TextField(blank=True, null=True)),
                ('enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'mcp_server',
                'ordering': ['name'],
            },
        ),
    ]
