# Generated by Django 5.2.5 on 2025-08-20 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mcpserver',
            name='headers_json',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mcpserver',
            name='query_params_json',
            field=models.TextField(blank=True, null=True),
        ),
    ]
